#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"

echo "~~~ Restoring cached directories"
for line in $(plugin_read_list RESTORE) ; do
  printf "  %s\n" $line
  buildkite-agent artifact download "$line" .
done
