#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"

echo "~~~ Saving caches"
for line in $(plugin_read_list SAVE) ; do
  printf "  %s\n" $line
  buildkite-agent artifact upload "$line"
done
